---
# tasks file for sshpassDownload

- name: deleting previous file
  file: 
    path: "{{ v_remotePath }}/{{ upload_this_file }}" 
    state: absent
  tags:
    - playme

- name: upload zip file "{{ upload_this_file }}"
  script: uploadSftp.sh "{{ v_usr }}" "{{ v_pass }}" "{{ v_server }}" "{{ v_remotePath }}" "{{ v_localPath }}" "{{ upload_this_file }}"
  tags:
    - playme
    
- name: checking if "{{ upload_this_file }}" exists
  stat:
    path: "{{ v_localPath }}/{{ upload_this_file }}"
  register: resultado
  tags:
    - playme

- debug: msg="yes, file uploaded OK."
  when: resultado.stat.exists == True
  tags:
    - playme

- debug: msg="error, error, the file is not in the place it should be."
  when: resultado.stat.exists == False or resultado.stat.exists is not defined
  tags:
    - playme
